"""REST endpoint for the marketing website demo chat.

Exposes ``POST /demo/chat`` which runs a slim version of the cheese agent
without CRM, payments or post-sale tools. Reservations are stored in memory.
"""

from __future__ import annotations

import logging
import uuid

import httpx
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from pydantic_ai.exceptions import ModelAPIError
from pydantic_ai.messages import ModelResponse, ToolCallPart

from chatbot.ai_agent.agent import FALLBACK_MODEL
from chatbot.ai_agent.chat_history import (
    load_history,
    save_assistant_message,
    save_user_message,
)
from chatbot.ai_agent.demo_agent import get_demo_agent
from chatbot.ai_agent.dependencies import AgentDeps
from chatbot.api.utils.security import get_api_key
from chatbot.db.services import services
from chatbot.erp.client import build_erp_client
from chatbot.messaging.telegram_notifier import notify_error
from chatbot.messaging.whatsapp import whatsapp_manager

logger = logging.getLogger(__name__)

router = APIRouter()

erp_client: httpx.AsyncClient = build_erp_client()

_PROVIDER_ERRORS = (ModelAPIError, httpx.TimeoutException, httpx.ConnectError)


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------


class DemoChatRequest(BaseModel):
    session_id: str | None = None
    message: str


class DemoChatResponse(BaseModel):
    session_id: str
    response: str
    tools_used: list[str]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _extract_tools_used(result) -> list[str]:
    """Extract tool names called during the agent run."""
    tools: list[str] = []
    for msg in result.all_messages():
        if isinstance(msg, ModelResponse):
            for part in msg.parts:
                if isinstance(part, ToolCallPart):
                    tools.append(part.tool_name)
    return tools


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------


@router.post("/chat", response_model=DemoChatResponse)
async def demo_chat(
    body: DemoChatRequest,
    _: bool = Depends(get_api_key),
) -> DemoChatResponse:
    """Run one turn of the demo cheese agent and return the response directly.

    - ``session_id`` is generated by the server if omitted.
    - Conversation history is persisted in the database keyed by ``session_id``.
    - Reservations are stored in memory and lost on server restart.
    """
    session_id: str = body.session_id or str(uuid.uuid4())
    message: str = body.message

    logger.info("[demo/chat] session=%s message=%.80s", session_id, message)

    deps = AgentDeps(
        erp_client=erp_client,
        db_services=services,
        whatsapp_client=whatsapp_manager,
        user_phone=session_id,
    )

    history = await load_history(services, session_id)
    await save_user_message(services, session_id, message)

    agent = get_demo_agent()

    try:
        result = await agent.run(message, deps=deps, message_history=history)
    except _PROVIDER_ERRORS as exc:
        logger.warning(
            "[demo/chat] Provider error on first attempt — retrying with fallback model. error=%s",
            exc,
        )
        try:
            result = await agent.run(
                message,
                deps=deps,
                message_history=history,
                model=FALLBACK_MODEL,
            )
        except Exception as retry_exc:
            logger.error(
                "[demo/chat] Fallback model also failed. session=%s error=%s",
                session_id,
                retry_exc,
                exc_info=True,
            )
            await notify_error(
                retry_exc,
                context=f"demo_chat fallback | session={session_id}",
            )
            raise HTTPException(
                status_code=500, detail="Internal server error"
            ) from retry_exc
    except Exception as exc:
        logger.error(
            "[demo/chat] Unexpected error. session=%s error=%s",
            session_id,
            exc,
            exc_info=True,
        )
        await notify_error(exc, context=f"demo_chat | session={session_id}")
        raise HTTPException(status_code=500, detail="Internal server error") from exc

    reply: str = result.output
    tools_used: list[str] = _extract_tools_used(result)

    await save_assistant_message(services, session_id, reply, tools_used)

    logger.info(
        "[demo/chat] session=%s tools=%s response=%.80s",
        session_id,
        tools_used,
        reply,
    )

    return DemoChatResponse(
        session_id=session_id,
        response=reply,
        tools_used=tools_used,
    )
