"""ERP transcript upload utilities.

Provides a function to upload user/bot message interactions to the ERP after
each WhatsApp conversation turn.
"""

from __future__ import annotations

import logging

import httpx

logger = logging.getLogger(__name__)

UPLOAD_TRANSCRIPT_ENDPOINT = (
    "/api/method/cheese.api.v1.message_controller.upload_message_transcript"
)


async def upload_message_transcript(
    client: httpx.AsyncClient,
    phone_number: str,
    user_message: str,
    bot_response: str,
) -> None:
    """Upload a user/bot interaction pair to the ERP.

    Args:
        client: Authenticated ERP httpx.AsyncClient.
        phone_number: User's WhatsApp phone number.
        user_message: The message sent by the user.
        bot_response: The response generated by the bot.
    """
    payload: dict = {
        "phone_number": phone_number,
        "messages": [
            {"role": "user", "content": user_message},
            {"role": "assistant", "content": bot_response},
        ],
    }

    logger.debug(
        "[transcript] Uploading transcript for %s | user=%s | bot=%s",
        phone_number,
        user_message[:80],
        bot_response[:80],
    )

    try:
        response = await client.post(UPLOAD_TRANSCRIPT_ENDPOINT, json=payload)
        response.raise_for_status()
        data = response.json()
        logger.info(
            "[transcript] Uploaded transcript for %s | result=%s",
            phone_number,
            data.get("message", {}).get("message", "ok"),
        )
    except httpx.HTTPStatusError as exc:
        logger.error(
            "[transcript] HTTP error uploading transcript for %s: %s - %s",
            phone_number,
            exc.response.status_code,
            exc.response.text,
        )
    except httpx.RequestError as exc:
        logger.error(
            "[transcript] Request error uploading transcript for %s: %s",
            phone_number,
            exc,
        )
