"""ERP transcript upload utilities.

Provides a function to upload user/bot message interactions to the ERP after
each WhatsApp conversation turn.
"""

from __future__ import annotations

import logging
from typing import Any

import httpx

from chatbot.ai_agent.tools.erp_utils import extract_erp_data

logger = logging.getLogger(__name__)

UPLOAD_TRANSCRIPT_ENDPOINT = (
    "/api/method/cheese.api.v1.message_controller.upload_message_transcript"
)

OPEN_OR_RESUME_CONVERSATION_ENDPOINT = (
    "/api/method/cheese.api.v1.conversation_controller.open_or_resume_conversation"
)

ERP_TIMEOUT_SECONDS: float = 15.0


async def _fetch_conversation_id(
    client: httpx.AsyncClient,
    phone_number: str,
    channel: str = "WhatsApp",
) -> str | None:
    """Call the ERP to open or resume a conversation and return the ID.

    Returns ``None`` if the ERP fails to provide a ``conversation_id``.

    Args:
        client: Authenticated ERP httpx.AsyncClient.
        phone_number: Contact identifier (phone number).
        channel: Communication channel.
    """
    logger.debug(
        "[_fetch_conversation_id] phone_number=%s channel=%s",
        phone_number,
        channel,
    )
    try:
        response = await client.post(
            OPEN_OR_RESUME_CONVERSATION_ENDPOINT,
            json={
                "contact_id": phone_number,
                "channel": channel,
                "status": "ACTIVE",
            },
            timeout=ERP_TIMEOUT_SECONDS,
        )
        response.raise_for_status()
        data: dict[str, Any] = extract_erp_data(response.json())
        conversation_id: str | None = data.get("conversation_id")
        logger.debug("[_fetch_conversation_id] conversation_id=%s", conversation_id)
        return conversation_id
    except httpx.HTTPStatusError as exc:
        # 422 con "active conversation already exists" es un bug conocido del ERP:
        # el endpoint debería devolver la conversación existente pero en su lugar lanza
        # VALIDATION_ERROR. La subida del transcript sigue funcionando sin conversation_id.
        if (
            exc.response.status_code == 422
            and "active conversation already exists" in exc.response.text.lower()
        ):
            logger.debug(
                "[_fetch_conversation_id] Active conversation already exists for %s, proceeding without conversation_id",
                phone_number,
            )
        else:
            logger.error(
                "[_fetch_conversation_id] HTTP error for %s: %s - %s",
                phone_number,
                exc.response.status_code,
                exc.response.text,
            )
    except httpx.RequestError as exc:
        logger.error(
            "[_fetch_conversation_id] Request error for %s: %s",
            phone_number,
            exc,
        )
    return None


async def upload_message_transcript(
    client: httpx.AsyncClient,
    phone_number: str,
    user_message: str,
    bot_response: str,
) -> None:
    """Upload a user/bot interaction pair to the ERP.

    Calls ``open_or_resume_conversation`` first to obtain the
    ``conversation_id`` and includes it in the payload.

    Args:
        client: Authenticated ERP httpx.AsyncClient.
        phone_number: User's WhatsApp phone number.
        user_message: The message sent by the user.
        bot_response: The response generated by the bot.
    """
    conversation_id = await _fetch_conversation_id(client, phone_number)

    payload: dict[str, Any] = {
        "phone_number": phone_number,
        "messages": [
            {"role": "user", "content": user_message},
            {"role": "assistant", "content": bot_response},
        ],
    }
    if conversation_id:
        payload["conversation_id"] = conversation_id

    logger.debug(
        "[transcript] Uploading transcript for %s | conversation_id=%s | user=%s | bot=%s",
        phone_number,
        conversation_id,
        user_message[:80],
        bot_response[:80],
    )

    try:
        response = await client.post(UPLOAD_TRANSCRIPT_ENDPOINT, json=payload)
        response.raise_for_status()
        data: dict[str, Any] = response.json()
        logger.info(
            "[transcript] Uploaded transcript for %s | result=%s",
            phone_number,
            data.get("message", {}).get("message", "ok"),
        )
    except httpx.HTTPStatusError as exc:
        logger.error(
            "[transcript] HTTP error uploading transcript for %s: %s - %s",
            phone_number,
            exc.response.status_code,
            exc.response.text,
        )
    except httpx.RequestError as exc:
        logger.error(
            "[transcript] Request error uploading transcript for %s: %s",
            phone_number,
            exc,
        )
